// <auto-generated />
using System;
using GranjaAvicolaD.app.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GranjaAvicolaD.app.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GranjaAvicolaD.app.Dominio.DatosInicioSesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Pasword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DatosInicioSesiones");
                });

            modelBuilder.Entity("GranjaAvicolaD.app.Dominio.Galpon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("NumeroGallinas")
                        .HasColumnType("int");

                    b.Property<int?>("OperarioId")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VeterinarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperarioId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("Galpones");
                });

            modelBuilder.Entity("GranjaAvicolaD.app.Dominio.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("CantidadAlimento")
                        .HasColumnType("real");

                    b.Property<int>("GallinasEnfermasPorCuarentena")
                        .HasColumnType("int");

                    b.Property<int?>("GalponId")
                        .HasColumnType("int");

                    b.Property<float>("NivelAgua")
                        .HasColumnType("real");

                    b.Property<float>("Temperatura")
                        .HasColumnType("real");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GalponId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Historias");
                });

            modelBuilder.Entity("GranjaAvicolaD.app.Dominio.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("GranjaAvicolaD.app.Dominio.Sugerencias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sugerencia");
                });

            modelBuilder.Entity("GranjaAvicolaD.app.Dominio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GranjaAvicolaD.app.Dominio.DatosInicioSesion", b =>
                {
                    b.HasOne("GranjaAvicolaD.app.Dominio.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GranjaAvicolaD.app.Dominio.Galpon", b =>
                {
                    b.HasOne("GranjaAvicolaD.app.Dominio.DatosInicioSesion", "Operario")
                        .WithMany()
                        .HasForeignKey("OperarioId");

                    b.HasOne("GranjaAvicolaD.app.Dominio.DatosInicioSesion", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId");

                    b.Navigation("Operario");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("GranjaAvicolaD.app.Dominio.Historia", b =>
                {
                    b.HasOne("GranjaAvicolaD.app.Dominio.Galpon", "Galpon")
                        .WithMany()
                        .HasForeignKey("GalponId");

                    b.HasOne("GranjaAvicolaD.app.Dominio.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Galpon");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GranjaAvicolaD.app.Dominio.Registro", b =>
                {
                    b.HasOne("GranjaAvicolaD.app.Dominio.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GranjaAvicolaD.app.Dominio.Sugerencias", b =>
                {
                    b.HasOne("GranjaAvicolaD.app.Dominio.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
